core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from two_factor.urls import urlpatterns as tf_urls
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('', include(tf_urls)),
    path('account/', include('account.urls', namespace='account')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('seller/', include('seller.urls', namespace='seller')),
    path('passwordreset', auth_views.PasswordResetView.as_view(
        template_name='account/registration/passwordreset.html'), name='reset_password'),
    path('passwordreset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='account/registration/passwordresetdone.html'), name='password_reset_done'),
    path("passwordreset-confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        template_name='account/registration/passwordresetconfirm.html'), name='password_reset_confirm'),
    path("passwordreset-complete", auth_views.PasswordResetCompleteView.as_view(
        template_name='account/registration/passwordresetcomplete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path

from . import views

app_name = 'seller'

urlpatterns = [
    path('', views.seller_home, name='seller_home'),
    path('become_seller/', views.become_seller, name='become_seller'), 
    path('show_products/', views.show_products, name='show_products'), 
    path('add_product/', views.add_product, name='add_product'),
    path('edit_product/<int:pk>/', views.edit_product, name='edit_product'),
    path('add_category/', views.add_category, name='add_category'),
]

seller/forms.py
from django import forms
from store.models import Product, Category
from account.models import UserBase
from account.models import Seller
from django.db.models import Q

class SellerRegistrationForm(forms.ModelForm):    
    class Meta:
        model = Seller
        fields = ('verification_document', )

class AddProductForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(AddProductForm, self).__init__(*args, **kwargs)

        # all fields except in stock are required
        for key in self.fields:
            self.fields[key].required = True
        
        self.fields['in_stock'].required = False

    class Meta:
        model = Product
        fields = ['title', 'category', 'image', 'image_alternate', 'price', 'in_stock']

class AddCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name']

    def clean_name(self):
        name = self.cleaned_data['name'].lower()
        r = Category.objects.filter(name=name)
        if r.count():
            raise forms.ValidationError("Category already exists")
        return name

seller/views.py
import logging
import urllib
import json
from account.models import UserBase
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from django.urls import reverse
from orders.models import Order
from store.models import Product

from .forms import AddCategoryForm, AddProductForm, SellerRegistrationForm

db_logger = logging.getLogger('db')


@login_required
def seller_home(request):
    orders = Order.objects.all()
    return render(request, 'seller/seller_home.html', {'orders': orders})


@login_required
def become_seller(request):
    if request.method == 'POST':
        form = SellerRegistrationForm(request.POST, request.FILES)
        if form.is_valid():
            user = UserBase.objects.get(pk=request.user.pk)
            user.verification_document = request.FILES['verification_document']
            user.user_type = 2  # make user as unverified seller
            user.save()
            messages.info(
                request, f'Your seller application has been sent to the Admin for approval')
            return redirect('store:store_home')
    else:
        form = SellerRegistrationForm()

    return render(request, 'seller/become_seller_form.html', {'form': form})


@login_required
def show_products(request):
    products = Product.objects.filter(created_by__id=request.user.id)
    return render(request, 'seller/show_products.html', {'products': products})


@login_required
def add_product(request):
    user = request.user
    if request.method == 'POST':
        form = AddProductForm(request.POST, request.FILES)
        if form.is_valid():
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            data = urllib.parse.urlencode(values).encode()
            req = urllib.request.Request(url, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
            if result['success']:
                product = form.save(commit=False)
                product.created_by = request.user
                product.save()
                messages.success(
                    request, f'Product {product.title} added successfully!')
                db_logger.info(
                    f"User: {user.user_name}, added product: {product.title}")
                return redirect('seller:seller_home')
            else:
                messages.warning(
                    request, 'Invalid reCAPTCHA. Please try again.')
                return redirect(reverse('seller:add_product'))

    else:
        form = AddProductForm()

    return render(request, 'seller/add_product.html', {'form': form})


@login_required
def edit_product(request, pk):
    product = Product.objects.get(id=pk)
    if request.method == 'POST':
        form = AddProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            data = urllib.parse.urlencode(values).encode()
            req = urllib.request.Request(url, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
            if result['success']:
                form.save()
                messages.success(
                    request, f'You have edited details of {product.title}')
                db_logger.info(
                    f"User: {request.user.user_name}, edited product: {product.title}")
                return redirect('seller:seller_home')
            else:
                messages.warning(
                    request, 'Invalid reCAPTCHA. Please try again.')
                return render(request, 'seller/edit_product.html', {'form': form})
    else:
        form = AddProductForm(instance=product)

    return render(request, 'seller/edit_product.html', {'form': form})


@login_required
def add_category(request):
    user = request.user
    if request.method == 'POST':
        form = AddCategoryForm(request.POST)
        if form.is_valid():
            recaptcha_response = request.POST.get('g-recaptcha-response')
            url = 'https://www.google.com/recaptcha/api/siteverify'
            values = {
                'secret': settings.GOOGLE_RECAPTCHA_SECRET_KEY,
                'response': recaptcha_response
            }
            data = urllib.parse.urlencode(values).encode()
            req = urllib.request.Request(url, data=data)
            response = urllib.request.urlopen(req)
            result = json.loads(response.read().decode())
            if result['success']:
                category = form.save(commit=False)
                category.name = form.cleaned_data['name']
                category.save()
                messages.success(request, f'Added new category: {category.name}')
                db_logger.info(
                    f"User: {user.user_name}, added category: {category.name}")
                return redirect('seller:seller_home')
            else:
                messages.warning(
                    request, 'Invalid reCAPTCHA. Please try again.')
                return render(request, 'seller/add_category.html', {'form': form})

    else:
        form = AddCategoryForm()

    return render(request, 'seller/add_category.html', {'form': form})

templates/seller/add_category.html
{% extends "../base.html" %} 
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <form method="post" enctype="multipart/form-data">
      <fieldset>
        <legend>Add Category</legend>
        {% csrf_token %}
        {{ form|crispy }}
        <script src='https://www.google.com/recaptcha/api.js'></script>
<div class="g-recaptcha" data-sitekey="6LfrWOccAAAAAKkaZsdEo62zYqpAKm_T92G8YG04"></div>
        <button type="submit">Add Category</button>
      </fieldset>
      </form>
</div>

{% endblock %}

templates/seller/add_product.html
{% extends "../base.html" %} 
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <form method="post" enctype="multipart/form-data">
        <h1 class="h2">Add Product</h1>
        {% csrf_token %}
        {{ form|crispy }}
        <script src='https://www.google.com/recaptcha/api.js'></script>
<div class="g-recaptcha" data-sitekey="6LfrWOccAAAAAKkaZsdEo62zYqpAKm_T92G8YG04"></div>
        <button type="submit">Add Product</button>
      </form>
</div>

{% endblock %}

templates/seller/become_seller_form.html
{% extends "../base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
  <fieldset>
    <legend>Fill form to become seller</legend>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form|crispy }}
      <script src='https://www.google.com/recaptcha/api.js'></script>
      <div class="g-recaptcha" data-sitekey="6LfrWOccAAAAAKkaZsdEo62zYqpAKm_T92G8YG04"></div>
      <button type="submit">Upload</button>
    </form>
  </fieldset>
</div>

{% endblock %}

templates/seller/edit_product.html
{% extends "../base.html" %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
  <form method="post" enctype="multipart/form-data">
    <fieldset>
      <legend>Edit Product Details</legend>
      {% csrf_token %}
      {{ form|crispy }}
      <script src='https://www.google.com/recaptcha/api.js'></script>
      <div class="g-recaptcha" data-sitekey="6LfrWOccAAAAAKkaZsdEo62zYqpAKm_T92G8YG04"></div>
      <button type="submit">Save changes</button>
    </fieldset>
  </form>
</div>

{% endblock %}

templates/seller/seller_home.html
{% extends "../base.html" %}

{% block content %}

<div class="container">
    <h1><strong>Seller Profile</strong> - {{ user.user_name }}</h1>
    <!-- if user == verified seller -->
    {% if user.user_type == 3 %}
    <p>You are a registered seller</p>
    <p><a href="{% url 'seller:show_products' %}">Look at your products</a></p>
    <p><a href="{% url 'seller:add_product' %}">Add Product</a></p>
    <p><a href="{% url 'seller:add_category' %}">Add Category</a></p>
    <div style="margin-left:20px;margin-top:20px">
        <h2>Your Past Orders</h2>
        <hr />
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Photo</th>
                    <th scope="col">Item</th>
                    <th scope="col">Qty</th>
                    <th scope="col">Total Cost</th>
                    <th scope="col">Status</th>
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}
                {% if order.product.created_by.id == user.id %}
                <tr class="{% if order.billing_status %} table-success {% else %} table-danger {% endif %}">
                    <td>{{ order.created }} </td>
                    <td><img class="img-fluid" width="100px" height="100px" alt="Responsive image"
                            src="{{ order.product.image.url }}"></td>
                    <td><a class="text-decoration-none"
                            href="{% url 'seller:edit_product' order.product.id %}">{{order.product|title}}</td>
                    <td>{{ order.quantity }}</td>
                    <td>&#8377 {{ order.total_paid }}</td>
                    <td>{% if order.billing_status %} Success {% else %} Failure {% endif %}</td>
                </tr>
                {% endif %}
                {% endfor%}
            </tbody>
        </table>

        {% else %}
        <div class="col-12">
            <!-- user == unverified seller -->
            {% if user.user_type == 2 %}
            <p>The admin is approving your request</p>
            {% else %}
            <!-- user == buyer -->
            <p>Want to become a seller ? Fill <a href="{% url 'seller:become_seller' %}">this form</a>.</p>
            {% endif %}
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

templates/seller/show_products.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <div class="container">
        <div class="row">
            <div class="album py-5">
                <!-- check if user == verified_seller -->
                {% if user.user_type == 3 %} 
                <div class="col-12">
                    <h1 class="h2">Your Products</h1>
                    <p>Click on the product to edit it.</p>
                    {% if not products %}
                    <div class="col-12">You have not added any product yet. Try adding a new Product.</div>
                    {% else %}
                    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
                        {% for product in products %}
                        <div class="col">
                            <div class="card border-0">
                                <img class="img-fluid" alt="Responsive image" src="{{ product.image.url }}">
                                <div class="card-body px-0">
                                    <p class="card-text">
                                        <a href="{% url 'seller:edit_product' product.id %}">{{ product.title }}</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
                {% else %}
                <div class="col-12">
                    <h1 class="h2">What da hell are you doing here ?</h1>
                    <p>You are not a seller :/</p>
                </div>
                {% endif %}

            </div>
        </div>
    </div>

    {% endblock %}