account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

# https://docs.djangoproject.com/en/3.1/topics/auth/default/
# https://ccbv.co.uk/projects/Django/3.0/django.contrib.auth.views/PasswordResetConfirmView/

app_name = 'account'

urlpatterns = [
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    # edit user details
    path('edit_user/<int:pk>/', views.edit_user, name='edit_user'),
    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from two_factor.urls import urlpatterns as tf_urls
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('', include(tf_urls)),
    path('account/', include('account.urls', namespace='account')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('seller/', include('seller.urls', namespace='seller')),
    path('passwordreset', auth_views.PasswordResetView.as_view(
        template_name='account/registration/passwordreset.html'), name='reset_password'),
    path('passwordreset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='account/registration/passwordresetdone.html'), name='password_reset_done'),
    path("passwordreset-confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(
        template_name='account/registration/passwordresetconfirm.html'), name='password_reset_confirm'),
    path("passwordreset-complete", auth_views.PasswordResetCompleteView.as_view(
        template_name='account/registration/passwordresetcomplete.html'), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path

from . import views

app_name = 'seller'

urlpatterns = [
    path('', views.seller_home, name='seller_home'),
    path('become_seller/', views.become_seller, name='become_seller'), 
    path('show_products/', views.show_products, name='show_products'), 
    path('add_product/', views.add_product, name='add_product'),
    path('edit_product/<int:pk>/', views.edit_product, name='edit_product'),
    path('add_category/', views.add_category, name='add_category'),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='store_home'),
    path('<int:pk>', views.product_detail, name='product_detail'),
    path('search/search_categories/<int:pk>', views.category_list, name='category_list'),
    path('search/search_products', views.search_products, name='search_products'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>FCS-Store</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous">
        </script>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/base.css' %}">
    <link rel="stylesheet" href="{% block stylesheet %}{% endblock %}">


    <style>
        .keyboard {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            padding: 5px 0;
            background: #ffffff;
            box-shadow: 0 0 50px rgba(0, 0, 0, 0.5);
            user-select: none;
            transition: bottom 0.4s;
        }

        .keyboard--hidden {
            bottom: -100%;
        }

        .keyboard__keys {
            text-align: center;
        }

        .keyboard__key {
            height: 45px;
            width: 6%;
            max-width: 90px;
            margin: 3px;
            border-radius: 4px;
            border: solid;
            background: rgba(255, 255, 255, 0.2);
            color: #050000;
            font-size: 1.05rem;
            outline: none;
            cursor: pointer;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            vertical-align: top;
            padding: 0;
            -webkit-tap-highlight-color: transparent;
            position: relative;
        }

        .keyboard__key:hover {
            background: rgb(243, 243, 243);
        }

        .keyboard__key:active {
            background: rgba(255, 255, 255, 0.12);
        }

        .keyboard__key--activatable::after {
            content: '';
            top: 10px;
            right: 10px;
            position: absolute;
            width: 8px;
            height: 8px;
            background: rgba(70, 238, 3, 0.925);
            border-radius: 50%;
        }

        .keyboard__key--active::after {
            background: #3a3a3a;
        }

        .keyboard__key--dark {
            background: rgba(85, 84, 84, 0.25);
        }
    </style>

    <script>
        const Keyboard = {
            elements: {
                main: null,
                keysContainer: null,
                keys: []
            },

            eventHandlers: {
                oninput: null,
                onclose: null
            },

            properties: {
                value: "",
                capsLock: false
            },

            init() {
                // Create main elements
                this.elements.main = document.createElement("div");
                this.elements.keysContainer = document.createElement("div");

                // Setup main elements
                this.elements.main.classList.add("keyboard", "keyboard--hidden");
                this.elements.keysContainer.classList.add("keyboard__keys");
                this.elements.keysContainer.appendChild(this._createKeys());

                this.elements.keys = this.elements.keysContainer.querySelectorAll(".keyboard__key");

                // Add to DOM
                this.elements.main.appendChild(this.elements.keysContainer);
                document.body.appendChild(this.elements.main);

                // Automatically use keyboard for elements with .use-keyboard-input
                document.querySelectorAll(".use-keyboard-input").forEach(element => {
                    element.addEventListener("focus", () => {
                        this.open(element.value, currentValue => {
                            element.value = currentValue;
                        });
                    });
                });
            },

            _createKeys() {
                const fragment = document.createDocumentFragment();
                const keyLayout = [
                    "`", "~", "!", "@", "#", "$", "%", "^", "&", "*", "(", ")", "-", "_", "+", "=",  "backspace", 
                    "1", "2", "3", "4", "5", "6", "7", "8", "9", "0", "{", "}", "|", 
                    "q", "w", "e", "r", "t", "y", "u", "i", "o", "p", "[", "]",  
                    "caps", "a", "s", "d", "f", "g", "h", "j", "k", "l", ":", ";", "'", "enter", 
                    "z", "x", "c", "v", "b", "n", "m", "<", ">", ",", ".", "/", "?", 
                    "done", "space",
                ];

                // Creates HTML for an icon
                const createIconHTML = (icon_name) => {
                    return `<i class="material-icons">${icon_name}</i>`;
                };

                keyLayout.forEach(key => {
                    const keyElement = document.createElement("button");
                    const insertLineBreak = ["backspace", "|", "]", "enter", "?", "space"].indexOf(key) !== -1;

                    // Add attributes/classes
                    keyElement.setAttribute("type", "button");
                    keyElement.classList.add("keyboard__key");

                    switch (key) {
                        case "backspace":
                            keyElement.innerHTML = createIconHTML("backspace");
                            keyElement.classList.add("keyboard__key--dark");
                            keyElement.addEventListener("click", () => {
                                this.properties.value = this.properties.value.substring(0, this.properties.value.length - 1);
                                this._triggerEvent("oninput");
                            });

                            break;

                        case "caps":
                            keyElement.classList.add("keyboard__key--activatable");
                            keyElement.innerHTML = createIconHTML("keyboard_capslock");
                            keyElement.classList.add("keyboard__key--dark");
                            keyElement.addEventListener("click", () => {
                                this._toggleCapsLock();
                                keyElement.classList.toggle("keyboard__key--active", this.properties.capsLock);
                            });

                            break;

                        case "enter":
                            keyElement.innerHTML = createIconHTML("keyboard_return");
                            keyElement.classList.add("keyboard__key--dark");
                            keyElement.addEventListener("click", () => {
                                this.properties.value += "\n";
                                this._triggerEvent("oninput");
                            });

                            break;

                        case "space":
                            keyElement.innerHTML = createIconHTML("space_bar");
                            keyElement.classList.add("keyboard__key--dark");
                            keyElement.addEventListener("click", () => {
                                this.properties.value += " ";
                                this._triggerEvent("oninput");
                            });

                            break;

                        case "done":
                            keyElement.classList.add("keyboard__key--dark");
                            keyElement.innerHTML = createIconHTML("check_circle");

                            keyElement.addEventListener("click", () => {
                                this.close();
                                this._triggerEvent("onclose");
                            });

                            break;

                        default:
                            keyElement.textContent = key.toLowerCase();

                            keyElement.addEventListener("click", () => {
                                this.properties.value += this.properties.capsLock ? key.toUpperCase() : key.toLowerCase();
                                this._triggerEvent("oninput");
                            });

                            break;
                    }

                    fragment.appendChild(keyElement);

                    if (insertLineBreak) {
                        fragment.appendChild(document.createElement("br"));
                    }
                });

                return fragment;
            },

            _triggerEvent(handlerName) {
                if (typeof this.eventHandlers[handlerName] == "function") {
                    this.eventHandlers[handlerName](this.properties.value);
                }
            },

            _toggleCapsLock() {
                this.properties.capsLock = !this.properties.capsLock;

                for (const key of this.elements.keys) {
                    if (key.childElementCount === 0) {
                        key.textContent = this.properties.capsLock ? key.textContent.toUpperCase() : key.textContent.toLowerCase();
                    }
                }
            },

            open(initialValue, oninput, onclose) {
                this.properties.value = initialValue || "";
                this.eventHandlers.oninput = oninput;
                this.eventHandlers.onclose = onclose;
                this.elements.main.classList.remove("keyboard--hidden");
            },

            close() {
                this.properties.value = "";
                this.eventHandlers.oninput = oninput;
                this.eventHandlers.onclose = onclose;
                this.elements.main.classList.add("keyboard--hidden");
            }
        };

        window.addEventListener("DOMContentLoaded", function () {
            Keyboard.init();
        });

    </script>


</head>

<body>
    <header>
        <nav class="navbar border-bottom">
            <div class="container-fluid justify-content-center">
                <!-- Show Search Bar -->
                <form class="d-flex w-50" method=POST action="{% url 'store:search_products' %}">
                    {% csrf_token %}
                    <input class="form-control me-2 " type="search" placeholder="Search Products and Categories"
                        aria-label="Search" name="searched">
                    <button class="btn btn-outline-secondary" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
                <ul class="sidebar-nav">
                    <li><a href="{% url 'store:store_home' %}">Home Page</a></li>
                    <ul class="sidebar-nav">
                        {% if user.is_authenticated %}
                        <li><strong>User: </strong>{{ user.user_name }}</li>
                        <li><a href="{% url 'account:logout' %}?next={{request.path}}">Logout</a></li>
                        <li><a href="{% url 'account:dashboard' %}"> My Buyer Profile</a></li>
                        <li><a href="{% url 'seller:seller_home' %}">My Seller Profile</a></li>
                        {% else %}
                        <li><a href="{% url 'two_factor:login' %}">Login</a></li>
                        {% endif %}
                    </ul>

                    <ul class="sidebar-nav">
                        <li><strong>Popular Categories</strong></li>
                        {% for c in categories %}
                        <li><a href="{% url 'store:category_list' c.pk %}">{{ c.name|title }}</a></li>
                        {% endfor %}
                        <li></li>
                    </ul>
                </ul>
            </div>
            <div class="col-sm-10 ">
                <!-- Show error messages on screen -->
                {% if messages %}
                {% for message in messages %}
                <div class="alert {{ message.tags }}" role="alert">
                    {{ message }}
                </div>
                {% endfor %}
                {% endif %}
                <div class="p-2">
                    {% block content %} {% endblock %}
                </div>
            </div>
        </div>
    </div>
    <hr>
    <footer>
        <p class="text-center">Built by T-21 for FCS course project :)</p>
    </footer>
</body>

</html>